#pragma once

#include <array>
#include <cstdint>
#include <vector>

namespace extrans {

constexpr int kTurnTileSize = 64;
constexpr int kTurnPhaseCount = 64;
constexpr int kRippleDirectionPrecision = 32;
constexpr int kRippleDriftPrecision = 4;

struct WaveFrame {
    std::int32_t height = 0;
    double omega = 0.0;
    double radianStart = 0.0;
    std::int32_t blendRatio = 0;
};

bool ValidateWaveParameters(std::int32_t width, std::int32_t maxHeight,
                            double maxOmega);
WaveFrame ComputeWaveFrame(std::uint64_t currentTime, std::uint64_t duration,
                           std::int32_t imageHeight,
                           std::int32_t maxHeight, double maxOmega,
                           std::int32_t waveType);

struct MosaicFrame {
    std::int32_t blockSize = 2;
    std::int32_t offsetX = 0;
    std::int32_t offsetY = 0;
    std::int32_t blendRatio = 0;
};

bool ValidateMosaicParameters(std::int32_t width, std::int32_t height,
                              std::int64_t maxBlockSize);
MosaicFrame ComputeMosaicFrame(std::uint64_t currentTime,
                               std::uint64_t duration, std::int32_t width,
                               std::int32_t height,
                               std::int32_t maxBlockSize);
std::int32_t ComputeMosaicSampleCoordinate(std::int32_t logicalCoordinate,
                                           std::int32_t imageSize,
                                           std::int32_t blockSize,
                                           std::int32_t offset);

bool IsFiniteRotateParameter(double value);
std::int32_t TruncateRotateCoordinate(double value);

struct TurnParameters {
    std::int32_t start = 0;
    std::int32_t length = 0;
    std::int32_t sourceX = 0;
    std::int32_t sourceY = 0;
    std::int32_t stepX = 0;
    std::int32_t stepY = 0;

    bool operator==(const TurnParameters &other) const {
        return start == other.start && length == other.length &&
               sourceX == other.sourceX && sourceY == other.sourceY &&
               stepX == other.stepX && stepY == other.stepY;
    }
};

using TurnTable =
    std::array<std::array<TurnParameters, kTurnTileSize>, kTurnPhaseCount>;

const TurnTable &GetTurnTable();
const std::array<std::int32_t, kTurnPhaseCount> &GetTurnGloss();
std::int32_t ComputeTurnGlobalPhase(std::uint64_t currentTime,
                                    std::uint64_t duration,
                                    std::int32_t width,
                                    std::int32_t height);
std::int32_t ComputeTurnTilePhase(std::int32_t globalPhase,
                                  std::int32_t tileX,
                                  std::int32_t tileY);

struct TurnPixelMapping {
    bool background = false;
    bool source2 = false;
    std::int32_t sourceX = 0;
    std::int32_t sourceY = 0;
    std::int32_t gloss = 0;
};

TurnPixelMapping MapTurnPixel(std::int32_t globalPhase,
                              std::int32_t logicalX,
                              std::int32_t logicalY);
std::uint32_t BlendARGB256(std::uint32_t source1, std::uint32_t source2,
                           std::int32_t ratio);
std::uint32_t ApplyTurnGloss(std::uint32_t color, std::int32_t gloss);

struct RippleParameters {
    std::int32_t width = 0;
    std::int32_t height = 0;
    std::int32_t centerX = 0;
    std::int32_t centerY = 0;
    std::int32_t rippleWidth = 128;
    float roundness = 1.0f;
    float speed = 6.0f;
    std::int32_t maxDrift = 24;
};

struct RippleTables {
    std::int32_t mapWidth = 0;
    std::int32_t mapHeight = 0;
    std::vector<std::uint16_t> displacement;
    // Unlike the Windows table, this does not duplicate the ripple-width
    // range. Callers wrap (distance + phase) explicitly.
    std::vector<std::uint16_t> drift;
};

struct RippleFrame {
    std::int32_t blendRatio = 0;
    std::int32_t phase = 0;
    std::int32_t drift = 0;
};

bool ValidateRippleParameters(const RippleParameters &parameters);
RippleTables GenerateRippleTables(const RippleParameters &parameters);
RippleFrame ComputeRippleFrame(std::uint64_t currentTime,
                               std::uint64_t duration,
                               const RippleParameters &parameters);

// RGBA8 helpers used by the lookup textures. Signed values are stored as a
// 24-bit magnitude plus a sign byte; all values generated by the official
// turn table fit in that range and therefore survive GLSL highp exactly.
std::uint32_t PackUnsigned16Pair(std::uint16_t first, std::uint16_t second);
std::uint32_t PackSigned24(std::int32_t value);
std::int32_t UnpackSigned24(std::uint32_t packed);

} // namespace extrans
